sudo: required
services: 
    - docker

before_install:
    - docker build -t dmitryshay/docker-learning -f Dockerfile.dev .

script:
    - docker run dmitryshay/docker-learning npm run test -- --coverage